name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install UV
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
    
    - name: Create and activate virtual environment
      run: |
        uv venv
        source .venv/bin/activate
    
    - name: Install dependencies
      run: |
        uv pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest
    
    - name: Run linting
      run: |
        ruff check .
        mypy .
    
    - name: Run formatting check
      run: |
        black --check .
        isort --check-only .

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Streamlit Cloud
      env:
        STREAMLIT_TOKEN: ${{ secrets.STREAMLIT_TOKEN }}
      run: |
        # Add Streamlit Cloud deployment steps here
        echo "Deployment will be configured once Streamlit Cloud is set up" 